desi_mart/urls.py
from django.urls import path,include
from django.contrib import admin
from . import views
from desi_mart.views import products,general,basket

app_name = 'desi_mart'
#adding the urls and the views method associated with the url path.
urlpatterns = [
    path('', views.general.home, name='homepage'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products', views.products.all_products, name='products'),
    path('products/<str:category>', views.products.category_products, name='category_products'),
    path('products/search/', views.products.search_products, name='search_products'),
    path('product/<int:id>', views.products.product_detail, name='product_detail'),
    path('basket_add/<int:product_id>/', views.basket.basket_add, name='basket_add'),
    path('basket_remove/<int:product_id>/', views.basket.basket_remove, name='basket_remove'),
    path('basket_detail/', views.basket.basket_detail, name='basket_detail'),
    path('signup/', views.general.signup, name='signup'),
    path('place_order/', views.general.place_order, name='place_order'),
    path('order/success', views.general.order_success, name='orderplaced'),
    path('orders/', views.general.order_list, name='orders'),
    path('myorders/<int:id>', views.general.myorders, name='myorders'),
    path('order/<int:id>/', views.general.order_detail, name='order_detail'),
    path('dashboard/', views.general.dashboard, name='dashboard'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('desi_mart.urls', namespace='desi_mart')),
    path('', RedirectView.as_view(url='')),

]

desi_mart/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Cart(models.Model):
    product = models.ForeignKey('desi_mart.Product', on_delete=models.CASCADE, related_name='carts')
    quantity = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product},{self.quantity},{self.created_date}'


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, )
    address = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email}, {self.address}'

    class Meta:
        db_table = 'customer'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Customer.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.customer.save()

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class LineItem(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey('desi_mart.Product', on_delete=models.CASCADE)
    cart = models.ForeignKey('desi_mart.Cart', on_delete=models.CASCADE)
    order = models.ForeignKey('desi_mart.Order', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity},{self.product},{self.cart},{self.order},{self.created_date}'


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    imageLink = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2)
    in_stock = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.title

class Order(models.Model):
    customer = models.ForeignKey('desi_mart.Customer', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.customer},{self.created_date}'

desi_mart/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Product

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=50)
    address = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 
        'address', 'first_name', 'last_name', )

class ProductForm (forms.ModelForm):
    name= forms.CharField(max_length=200)

    class Meta:
        model = Product
        fields = ('name','price',)

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class BasketAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

desi_mart/views/basket.py
from decimal import Decimal
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST
from desi_mart.models import Product
from desi_mart.forms import BasketAddProductForm

class Basket(object):
    # a data transfer object to shift items from cart to page
    # inspired by Django 3 by Example (2020) by Antonio Mele
    # https://github.com/PacktPublishing/Django-3-by-Example/
    
    def __init__(self, request):
        self.session = request.session
        basket = self.session.get(settings.BASKET_SESSION_ID)
        if not basket:
            # save an empty basket in the session
            basket = self.session[settings.BASKET_SESSION_ID] = {}
        self.basket = basket

    def __iter__(self):
        """
        Iterate over the items in the basket and get the products
        from the database.
        """
        print(f'basket: { self.basket }')
        product_ids = self.basket.keys()
        # get the product objects and add them to the basket
        products = Product.objects.filter(id__in=product_ids)

        basket = self.basket.copy()
        for product in products:
            basket[str(product.id)]['product'] = product
            basket[str(product.id)]['product_id'] = product.id

        for item in basket.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def __len__(self):
        """
        Count all items in the basket.
        """
        return sum(item['quantity'] for item in self.basket.values())

    def add(self, product, quantity=1, override_quantity=False):
        """
        Add a product to the basket or update its quantity.
        """
        product_id = str(product.id)
        if product_id not in self.basket:
            self.basket[product_id] = {'quantity': 0,
                                      'price': str(product.discount_price),
                                       'title': product.title,
                                       'id': product.id,'image':product.imageLink}
        if override_quantity:
            self.basket[product_id]['quantity'] = quantity
        else:
            self.basket[product_id]['quantity'] += quantity
        self.save()

    def save(self):
        # mark the session as "modified" to make sure it gets saved
        self.session.modified = True

    def remove(self, product):
        """
        Remove a product from the basket.
        """
        product_id = str(product.id)
        if product_id in self.basket:
            del self.basket[product_id]
            self.save()

    def clear(self):
        # remove basket from session
        del self.session[settings.BASKET_SESSION_ID]
        self.save()

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.basket.values())


@require_POST
def basket_add(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    form = BasketAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        basket.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('desi_mart:basket_detail')

@require_POST
def basket_remove(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.remove(product)
    return redirect('desi_mart:basket_detail')

def basket_detail(request):
    basket = Basket(request)
    for item in basket:
        item['update_quantity_form'] = BasketAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    return render(request, 'desi_mart/basket.html', {'basket': basket})

desi_mart/views/general.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from desi_mart.models import Category, Product, Order, Customer, Cart, LineItem
from desi_mart.forms import SignUpForm
from django.contrib.auth.models import User


import random

from desi_mart.views.basket import Basket


def categories(request):
    return {
        'categories': Category.objects.all()
    }

def signup(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()
        user.customer.first_name = form.cleaned_data.get('first_name')
        user.customer.last_name = form.cleaned_data.get('last_name')
        user.customer.address = form.cleaned_data.get('address')
        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password= password)
        login(request, user)
        return redirect('/')
    return render(request, 'desi_mart/signup.html', {'form': form})

def home(request):
    return render(request,"desi_mart/homepage.html")


def place_order(request):
    basket = Basket(request)
    if request.method == "POST":
        address_data = request.POST.dict()
        first_name = address_data.get("first_name")
        last_name = address_data.get("last_name")
        email = address_data.get("email")
        address = address_data.get("address")
        return render(request, 'desi_mart/checkout.html', {'basket': basket, 'address': address, 'first_name': first_name, 'last_name': last_name, 'email':email})
    if request.user.is_authenticated:
        user = request.user
        return render(request, 'desi_mart/checkout.html', {'basket': basket})
    else:
        return  render(request, 'desi_mart/address_info.html', {'basket': basket})


def order_success(request):
    basket = Basket(request)
    user = request.user
    if user.is_authenticated:
        customer = get_object_or_404(Customer, user_id=user.id)
        order = Order.objects.create(customer=customer)
        order.refresh_from_db()
        for item in basket:
            product_item = get_object_or_404(Product, id=item['product_id'])
            cart = Cart.objects.create(product = product_item, quantity=item['quantity'])
            cart.refresh_from_db()
            line_item = LineItem.objects.create(quantity=item['quantity'], product=product_item, cart=cart,  order = order)
            line_item.refresh_from_db()

    basket.clear()
    request.session['deleted'] = 'thanks for your purchase'
    return render(request,'desi_mart/orderplaced.html')


def order_list(request):
    orders = Order.objects.all()
    return render(request, 'desi_mart/orders_list.html', {'orders' : orders})

def myorders(request,id):
    customer = get_object_or_404(Customer, user_id=id)
    orders = Order.objects.filter(customer=customer)
    return render(request, 'desi_mart/orders_list.html', {'orders' : orders})



def order_detail(request, id):
    order = get_object_or_404(Order, id=id)
    customer = order.customer
    user = get_object_or_404(User, id=customer.pk)
    line_items = LineItem.objects.filter(order_id=order.id)
    return render(request, 'desi_mart/order_detail.html', {'order' : order, 'user': user, 'line_items': line_items})


@login_required
def dashboard(request):
    user = request.user
    if user.is_authenticated & user.is_staff:
        dataset = [];
        for x in range(0,14):
            num = random.randrange(10,100)
            dataset.append(num)
        return render(request, 'desi_mart/dashboard.html',{'dataset': dataset})
    else:
        return redirect('desi_mart:login')

desi_mart/views/products.py
from django.shortcuts import get_object_or_404, render

from desi_mart.forms import BasketAddProductForm
from desi_mart.models import Category, Product
import random


def all_products(request):
    products = Product.objects.all()
    return render(request, 'desi_mart/products.html', {'products': products})


def category_products(request, category):
    category_obj = get_object_or_404(Category, name=category)
    products = Product.objects.filter(category=category_obj.id)
    return render(request,"desi_mart/products.html", {'products': products})


def search_products(request):
    search_query = request.GET['query']
    products = Product.objects.filter(title__icontains=search_query)
    return render(request,"desi_mart/products.html", {'products': products})


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    products = Product.objects.filter(category=product.category)
    start = random.randrange(1, len(products))
    if len(products)-start>5:
        end = start+5
    else:
        end = len(products)
    return render(request,"desi_mart/product_detail.html", {'product': product, 'products': products[start:end], 'basket_product_form' :BasketAddProductForm()})

desi_mart/templates/desi_mart/address_info.html
{% extends './base.html' %}
{% block content %}


<div class="container" style="background-color:white; margin-top:8%" >
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <h3>Address details: </h3>
                <form action="{% url 'desi_mart:place_order' %}" method="post" style="border: 5px solid #f1f1f1;background-color:#ffffe6;">
                    <div class="container" style="padding: 16px;">
                    {% csrf_token %}
                        <label class="form-label" for="name"><b>First name:*</b></label>
                        <input type="text" placeholder="Enter Fullname" name="first_name" style="margin:10px" required>
                        <br>

                        <label class="form-label"for="name"><b>Last name:*</b></label>
                        <input type="text" placeholder="Enter Fullname" name="last_name" style="margin:10px" required> <br>

                        <label class="form-label" for="email"><b>Email Id:*</b></label>
                        <input type="text" placeholder="Enter Email" name="email" style="margin:10px" required> <br>

                         <label class="form-label" for="address"><b>Address:*</b></label>
                         <input type="text" placeholder="Enter Address" name="address" style="margin:10px" required> <br>
                    <button class="btn btn-primary btn-sm" type="submit">Save address </button>
        </div>
                </form>
            </div>
            <div class="col-md-5 col-lg-5 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">Billing Summary</h1>
                <p><span class="lead">Total:£{{ basket.get_total_price }}</span> </p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Total cart price:</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ basket.get_total_price }}</span></div>
                            <div class="col-6">Delivery type:</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">Cash on delivery</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <button type="button" class="btn btn-primary btn-sm" disabled>Place order</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
 {% endblock %}

desi_mart/templates/desi_mart/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    {% block style %} {%endblock %}
</head>

<body style="background-image: url('https://previews.123rf.com/images/kasia2003/kasia20032110/kasia2003211000534/175971986-legumes-lentils-chickpea-beans-assortment-tasty-appetizing-ingredients-spices-grocery-for.jpg'); background-repeat: no-repeat; background-size: cover;">
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">DESIMART</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Category
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'desi_mart:products' %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.name == c.name %} class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{% url 'desi_mart:category_products' c.name %}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li>
                             <form class="d-flex" " action="{% url 'desi_mart:search_products' %}" method="get">
                        <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                     </form>
                        </li>


                    </ul>
                <ul class="navbar-nav me-auto mb-4 mb-md-0" style="margin-left:30%;">

                    {% if user.is_staff %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Admin tools
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="{% url 'desi_mart:dashboard' %}">Dashboard</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="{% url 'desi_mart:orders' %}">All Orders</a>
                        </li>
                            </ul>
                        </li>

                         {% endif %}

                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="{% url 'desi_mart:myorders' user.id %}">View orders</a>
                        </li>
                    <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="{% url 'desi_mart:logout' %}">Log Out</a>
                        </li>

                        {% else %}
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="{% url 'desi_mart:login' %}">Log in/sign up</a>
                        </li>

                    {% endif %}
                </ul>
                    <a type="button" role="button" href="{% url 'desi_mart:basket_detail' %}"
                        class="btn btn-outline-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="16" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        Basket
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
            <div id="content">{% block content %} {% endblock %}</div>

    </div>
</body>
</html>

desi_mart/templates/desi_mart/basket.html
{% extends './base.html' %}
{% block content %}

<main class="pt-5">
  <div class="container" style="background-color:white">

    <div class="col-12 text-end">
      <button type="button" onclick="location.href='{% url 'desi_mart:products' %}'" class="btn btn-primary btn-sm" style="margin:10px">Continue shopping</button>
    </div>
     <h1 class="h3">Shopping basket</h1>
    {% for item in basket %}
    {% with product=item.product %}
    <div data-index="{{item.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="150px" alt="Responsive image" src="{{item.image}}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10" >
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2"><a href="{% url 'desi_mart:product_detail' item.id %}">{{ item.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Item price</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">£{{ item.price }}</span></div>
            </div>
            <div class="row p-3">
              <div class="col-6">Total item price</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">£{{ item.total_price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">

                <table>
                  <tr>
                    <td><label >Qty</label></td>
                    <td>
                      <form action="{% url 'desi_mart:basket_add' item.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                      </form>
                    </td>
                    <td>
                      <form action="{% url 'desi_mart:basket_remove' item.id %}" method="post">
                        <input type="submit" value="Remove">
                        {% csrf_token %}
                      </form>
                    </td>
                  </tr>
                  </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: £<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>

      {% if user.is_authenticated %}
      <button type="button" onclick="location.href='{% url 'desi_mart:place_order' %}'" class="btn btn-primary btn-sm" style="margin:10px">Check out</button>
       {% else %}
      <p>Please login:      <button type="button" onclick="location.href='{% url 'desi_mart:login' %}'" class="btn btn-primary btn-sm" style="margin:10px">Log in</button>
      <br>
      <p>Continue as guest:  <button type="button" onclick="location.href='{% url 'desi_mart:place_order' %}'" class="btn btn-primary btn-sm" style="margin:10px">Check out</button></p>
   {% endif %}

    </div>
  </div>
</main>
 {% endblock %}

desi_mart/templates/desi_mart/homepage.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold" style="color:white"><u><i>Desi Mart</i></u></h1>
        <h2 class="h2 fw-bold" >Search, Add, Order !!!</h2>
        <p class=" fw-bold" style="color: rgba(255,255,255, 1)">Desi mart brings all the indian products to your doorstep.It is a one stop destination to find everything Indian. Order now to make the spicy butter chicken.</p>
        <p>
          <a href="{% url 'desi_mart:products' %}" class="btn btn-primary my-2">View all products</a>
        </p>
      </div>
    </div>
  </section>



</main>

{% endblock %}

desi_mart/templates/desi_mart/orders_list.html
  {% extends './base.html' %}
  {% block content %}

  <div class="container" style="background-color:white; margin-top:3%">
     <h1 class="mb-0 h2">Order List</h1>
                <p><span class="lead">{{user.first_name}}</span> (user)</p>
    
    {% for order in orders %}
    <div class="col border-bottom">
                        <div class="row p-3">

                              <p>
                                This is order {{order.id }}. The order was placed on: {{ order.created_date }}   <button type="button" onclick="location.href='{% url 'desi_mart:order_detail' id=order.id %}' " class="btn btn-primary btn-sm" style="margin:10px">View Order</button>

                              </p>


                        </div>
                    </div>
    {% endfor %}

  </div>

    {% endblock %}

desi_mart/templates/desi_mart/product_detail.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3" style="margin-left:15%">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.imageLink }}">
            </div>
            <div class="col-md-5 col-lg-5 ps-md-3 ps-lg-5" style="background-color:white">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.price }}£</span> (price)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Original Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                            <div class="col-6">Discount Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.discount_price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                             <form action="{% url 'desi_mart:basket_add' product.id %}" method="post">
                                      {{ basket_product_form }}
                                      {% csrf_token %}
                                      <input type="submit" class="btn btn-primary btn-sm" style="margin-left:50%" value="Add to Basket">
                             </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <br> <br>
        <div class="album py-5 bg-light">
            <div class="container">

              <div class="pb-3 h5">Similar Products</div>
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

                {% for product in products %}

                <div class="col">
                  <div class="card shadow-sm">
                      <a class="text-dark text-decoration-none" href="{% url 'desi_mart:product_detail' product.id %}"> <img class="img-fluid" alt="Responsive image" src="{{ product.imageLink}}"></a>
                    <div class="card-body">
                      <p class="card-text">
                        <a class="text-dark text-decoration-none" href="{% url 'desi_mart:product_detail' product.id %}">{{ product.title }}</a>
                      </p>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">£{{ product.discount_price }} </small>
                        <button type="button" onclick="location.href='{% url 'desi_mart:product_detail' product.id %}'" class="btn btn-primary btn-sm">view details</button>
                      </div>
                    </div>
                  </div>
                </div>

                {% endfor %}

              </div>
            </div>
          </div>
    </main>

</div>
{% endblock %}